version: "3.9"

networks:
  application:

services:
  site:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      MYSQL_DATABASE: books
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ../src/:/var/www/html:delegated
      - ../infra/docker/storage/nginx/logs:/var/log/nginx:delegated
      - ../infra/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ../infra/docker/nginx/mime.types:/etc/nginx/mime.types:cached
      - ../infra/docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:cached
      - ../infra/docker/nginx/certs.d:/etc/nginx/certs.d:ro
    depends_on:
      - php
      - mysql
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - application

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    command: --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: books
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ../infra/docker/storage/mysql:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost --password=secret || exit 1" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    networks:
      - application

  redis:
     image: redis:6.2.6
     container_name: redis
     restart: always
     logging:
       driver: "json-file"
       options:
         max-file: "3"
         max-size: "10m"
     networks:
       - application

  php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: php
    volumes:
      - ../src/:/var/www/html:delegated
      - ../infra/docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - ../infra/docker/php/php.ini:/usr/local/etc/php/php.ini:cached
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - application

  composer:
    build:
      context: .
      dockerfile: docker/composer.dockerfile
    container_name: composer
    volumes:
      - ../src/:/var/www/html
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - application

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ../src/:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - application

  artisan:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: artisan
    volumes:
      - ../src/:/var/www/html:delegated
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - application

  cron:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: cron
    volumes:
      - ../src/:/var/www/html:delegated
      - ../infra/docker/crontab:/etc/crontabs/laravel:delegated
    working_dir: /var/www/html
    # init: true
    entrypoint: ['crond', '-f', '-l', '8', '-L', '/dev/stdout']
    networks:
      - application

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 128M
    networks:
      - application

